name: Build and Test

on:
  push:
    branches: [ main, development, frontend_development ]
  pull_request:
    branches: [ main, development, frontend_development ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout code
    - name: Checkout repository
      uses: actions/checkout@v4
      
    # Step 2: Setup Node.js for React
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '19'
        
    # Step 3: Install React dependencies
    - name: Install React dependencies
      working-directory: ./frontend
      run: npm install
      
    # Step 4: Build React app
    - name: Build React app
      working-directory: ./frontend
      run: npm run build
      env:
        CI: false
        
    # Step 5: Setup Go
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25.1'
        
    # Step 6: Install Go dependencies
    - name: Install Go dependencies
      working-directory: ./backend
      run: go mod download
      
    # Step 7: Build Go app
    - name: Build Go app
      working-directory: ./backend
      run: go build -v ./...
   